# Generated by Django 4.2.1 on 2023-05-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_user_alter_post_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
