# Generated by Django 4.2.1 on 2023-05-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_comment_comment_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
